swaggerBaseUrl: ${SWAGGER_BASE_URL:http://localhost:8082}

server:
  port : 8082

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    resolve-schema-properties: true

spring:
  application:
    name: backend
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_STRING:mongodb://localhost:27017/mongo1}
      database: ${MONGODB_DATABASE:BackendDB}

database:
  collections:
    client: Client
    company: Company

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true