version: '2.1'
services:
  mongo1:
    image: mongo:4.2.8
    container_name: mongo1
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    healthcheck:
      test: echo 'rs.status().ok' | mongo localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - .:/scripts
    entrypoint: [ "bash", "/scripts/mongo_start.sh" ]

volumes:
  MONGO_DATA: